# Generated by Django 4.0.5 on 2022-07-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='article.article'),
        ),
    ]
