# Generated by Django 4.0.5 on 2022-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='answers',
            field=models.JSONField(null=True),
        ),
    ]
