# Generated by Django 4.0.5 on 2022-06-16 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0002_alter_test_answers_alter_testquestion_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
