# Generated by Django 4.0.5 on 2022-06-16 15:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0003_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
