# Generated by Django 4.0.5 on 2022-07-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0004_alter_test_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='description',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(default=1, upload_to='psychology/images/tests'),
            preserve_default=False,
        ),
    ]
