# Generated by Django 4.0.5 on 2022-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0006_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=3),
        ),
    ]
