# Generated by Django 4.0.5 on 2022-07-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0007_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
