# Generated by Django 4.0.5 on 2022-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0008_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
