# Generated by Django 4.0.5 on 2022-07-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0011_alter_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
