# Generated by Django 4.0.5 on 2022-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
