# Generated by Django 4.0.5 on 2022-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_alter_symptomformulaoption_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomformula',
            name='gender',
            field=models.CharField(choices=[('B', 'both'), ('M', 'male'), ('F', 'female')], default='B', max_length=5),
        ),
    ]
